### PR TITLE
Pages

### PR DESCRIPTION
**Pull request by AlejandroNeira98**
### In this part of the project the main changes were:

1. Deploying the project with GitHub Pages 
2. Adding the link to the README.md file

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @AlejandroNeira98 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- descriptive commit messages✔️
- correctly deployed your portfolio using Github pages✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!



# Required Changes ♻️

- [ ] **Required:** You pages load excellently on most device sizes, however, I noticed your page doesn't load well on **desktop/laptop with a screen width > 1100.**
image

You can fix this bug by only specifying the `min-width` to query all devices greater than that width.
**Hint:**
image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShoiraTa — CHANGES_REQUESTED** [review]
Hi @AlejandroNeira98 

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [ ] Please check the page on a bigger screen size, it looks like the recent changes have introduced a bug, everything looks great except the header: 

image

> This is happening because `.hey h1`   has   ` font-size: 5.5vw;`, so when the screen gets bigger than 1244px, the font is increasing accordingly and at some point it has no space to expand other than to wrap and overlap the text. You can simply fix this by changing the h1's `font-size`.

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AlejandroNeira98** [comment]
As it says in the README file, the desktop Version goes from 992px to 1100p, and that is due to the specifications of the previous project.

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi again @AlejandroNeira98 ,  

Your project is complete! Congratulations!  🎉💯🌟 
Sorry if I made you confused or if you found my argument irrelevant, your page looks great now 🤗 



Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
